CREATE DATABASE ThietKeCSDL;

USE ThietKeCSDL;

CREATE TABLE DSHS(
MaHS VARCHAR(255) NOT NULL PRIMARY KEY,
Ho TEXT,
Ten TEXT,
Nu TINYINT DEFAULT 1,
NgaySinh DATE,
Lop TEXT,
GhiChu TEXT
);

CREATE TABLE Lop(
Lop VARCHAR(255) PRIMARY KEY,
GVCN TEXT
);

CREATE TABLE Diem(
MaHS VARCHAR(255) PRIMARY KEY,
DiemToan DECIMAL(2,1),
DiemLy DECIMAL(2,1),
DiemHoa DECIMAL(2,1),
DiemVan DECIMAL(2,1),
DTB DECIMAL(4,2) GENERATED ALWAYS AS (( DiemToan + DiemLy + DiemHoa + DiemVan) / 4 ) STORED,
XepLoai TEXT
GENERATED ALWAYS AS (
	CASE
    WHEN (( DiemToan + DiemLy + DiemHoa + DiemVan) / 4 ) >= 8 THEN 'Gioi'
    WHEN (( DiemToan + DiemLy + DiemHoa + DiemVan) / 4 ) >= 6.5 THEN 'Kha'
    WHEN (( DiemToan + DiemLy + DiemHoa + DiemVan) / 4 ) >= 5 THEN 'TB'
    ELSE 'Yeu'
    END
    )STORED
);

SELECT MaHS, CONCAT(Ho,' ',Ten) AS HoTen, NgaySinh
FROM DSHS;

SELECT MaHS, CONCAT(Ho,' ',Ten) AS HoTen, NgaySinh
FROM DSHS
WHERE DAY(NgaySinh) = 20;

SELECT MaHS, CONCAT(Ho,' ',Ten) AS HoTen, NgaySinh
FROM DSHS
WHERE NgaySinh = '1999-09-06';

SELECT MaHS, CONCAT(Ho,' ',Ten) AS HoTen
FROM DSHS
WHERE Ten = 'NA';

SELECT MaHS, CONCAT(Ho,' ',Ten) AS HoTen
FROM DSHS
WHERE Ten LIKE 'N%';

SELECT MaHS, CONCAT(Ho,' ',Ten) AS HoTen
FROM DSHS
WHERE Ten LIKE '%NA%';

SELECT COUNT(*) AS SoLuong
FROM DSHS
WHERE Ten LIKE 'N%';

SELECT CONCAT(Ho,' ',Ten) AS HoTen, NgaySinh, DSHS.Lop, GVCN
FROM DSHS
JOIN LOP ON DSHS.Lop = LOP.Lop;

SELECT CONCAT(Ho,' ',Ten) AS HoTen, NgaySinh, DTB, XepLoai
FROM DSHS
JOIN DIEM ON DSHS.MaHS = DIEM.MaHS;

SELECT Lop, COUNT(*) AS SoLuong
FROM DSHS
GROUP BY Lop;

SELECT Lop, COUNT(*) AS SoLuong
FROM DSHS
GROUP BY Lop
HAVING COUNT(*) > 5;

SELECT Lop, COUNT(*) AS SoLuong
FROM DSHS
GROUP BY Lop
ORDER BY SoLuong DESC
LIMIT 1;

SELECT DSHS.MaHS, CONCAT(Ho,' ',Ten) AS HoTen, DTB
FROM DIEM
JOIN DSHS ON DSHS.MaHS = DIEM.MaHS
WHERE DTB = (SELECT MAX(DTB) FROM DIEM);

SELECT DSHS.MaHS, CONCAT(Ho,' ',Ten) AS HoTen, DTB
FROM DIEM
JOIN DSHS ON DSHS.MaHS = DIEM.MaHS
WHERE DTB > 8;

SELECT SUM(DTB) AS TongDTB
FROM DIEM
JOIN DSHS ON DSHS.MaHS = DIEM.MaHS
WHERE Ten LIKE 'NA%';

SELECT DSHS.MaHS, CONCAT(Ho,' ',Ten) AS HoTen, DTB, DiemToan
FROM DIEM
JOIN DSHS ON DSHS.MaHS = DIEM.MaHS
WHERE DTB > 5 AND DiemToan > 8;

SELECT DSHS.MaHS, CONCAT(Ho,' ',Ten) AS HoTen, XepLoai
FROM DIEM
JOIN DSHS ON DSHS.MaHS = DIEM.MaHS
WHERE XepLoai = 'Giỏi';

SELECT COUNT(*) AS SoLuongGioi
FROM DIEM
WHERE XepLoai = 'Giỏi';

SELECT DSHS.Lop, COUNT(*) AS SoLuongGioi
FROM DIEM
JOIN DSHS ON DIEM.MaHS = DSHS.MaHS
WHERE XepLoai = 'Giỏi'
GROUP BY DSHS.Lop;

SELECT MaHS, CONCAT(Ho,' ',Ten) AS HoTen
FROM DSHS
WHERE MaHS NOT IN (SELECT MaHS FROM DIEM);

SELECT DSHS.Lop, CONCAT(Ho,' ',Ten) AS HoTen, DTB
FROM DSHS
JOIN DIEM ON DSHS.MaHS = DIEM.MaHS
WHERE DTB IN (
    SELECT MAX(DTB)
    FROM DIEM d
    JOIN DSHS s ON d.MaHS = s.MaHS
    GROUP BY s.Lop
);